### ISSUE TITLE
mint nft error 

### ISSUE THREAD

**Issue by ghost** [shareslake/cardanocli-js#54]
hi im trying to mint a nft with this script  but cant get to work , i belive  is those files index.js and helper .js any one can help?
thanks

option --tx-out: 
unexpected "u"
expecting white space or multi-asset value expression

Build a transaction (low-level, inconvenient)

  Please note the order of some cmd options is crucial. If used incorrectly may produce undesired tx body. See nested [] notation above for details.
child_process.js:866
    throw err;
    ^

Error: Command failed: cardano-cli transaction build-raw                 --alonzo-era                 --tx-in

protocolParams.json                 
option --tx-out: 
unexpected "u"
expecting white space or multi-asset value expression

    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at CardanocliJs.transactionBuildRaw (/home/Downloads/nft-mint3/node_modules/cardanocli-js/index.js:904:5)
    at buildTransaction (/home/Downloads/nft-mint3/scr/mint-multiple-assets2.js:61:25)
    at Object.<anonymous> (/home/Downloads/nft-mint3/scr/mint-multiple-assets2.js:72:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {

**Comment by miguelaeh** [comment]
Hi @cryptoproun ,
I think this is related to https://github.com/shareslake/cardanocli-js/pull/53
Could you give a try?

**Comment by Amantis-whales** [comment]
hi @miguelaeh my code was diferent i changed but not realy work 

option --tx-out: 
unexpected "u"
expecting white space or multi-asset value expression

**Comment by ghost** [comment]
hi @miguelaeh my code was diferent i changed but not realy work

```
option --tx-out:
unexpected "u"
expecting white space or multi-asset value expression




at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at CardanocliJs.transactionBuildRaw (/home/amantis/Downloads/nft-mint3/node_modules/cardanocli-js/index.js:904:5)
    at buildTransaction (/home/Downloads/nft-mint3/scr/mint-multiple-assets2.js:61:25)
    at Object.<anonymous> (/home/Downloads/nft-mint3/scr/mint-multiple-assets2.js:72:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(3077) [Uint8Array] [
      111, 112, 116, 105, 111, 110,  32,  45,  45, 116, 120,  45,
      111, 117, 116,  58,  32,  10, 117, 110, 101, 120, 112, 101,
       99, 116, 101, 100,  32,  34, 117,  34,  10, 101, 120, 112,
      101,  99, 116, 105, 110, 103,  32, 119, 104, 105, 116, 101,
       32, 115, 112,  97,  99, 101,  32, 111, 114,  32, 109, 117,
      108, 116, 105,  45,  97, 115, 115, 101, 116,  32, 118,  97,
      108, 117, 101,  32, 101, 120, 112, 114, 101, 115, 115, 105,
      111, 110,  10,  10,  85, 115,  97, 103, 101,  58,  32,  99,
       97, 114, 100,  97,
      ... 2977 more items
    ]
  ],
  pid: 45676,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(3077) [Uint8Array] [
    111, 112, 116, 105, 111, 110,  32,  45,  45, 116, 120,  45,
    111, 117, 116,  58,  32,  10, 117, 110, 101, 120, 112, 101,
     99, 116, 101, 100,  32,  34, 117,  34,  10, 101, 120, 112,
    101,  99, 116, 105, 110, 103,  32, 119, 104, 105, 116, 101,
     32, 115, 112,  97,  99, 101,  32, 111, 114,  32, 109, 117,
    108, 116, 105,  45,  97, 115, 115, 101, 116,  32, 118,  97,
    108, 117, 101,  32, 101, 120, 112, 114, 101, 115, 115, 105,
    111, 110,  10,  10,  85, 115,  97, 103, 101,  58,  32,  99,
     97, 114, 100,  97,
    ... 2977 more items
  ]
}
```

**Comment by miguelaeh** [comment]
Could you share your code?

**Comment by ghost** [comment]
Hey @miguelaeh index and helper .js files that im using thanks! if u need more info please let me know [index-helper.js.zip](https://github.com/shareslake/cardanocli-js/files/8886446/index-helper.js.zip)

**Comment by miguelaeh** [comment]
@cryptoproun I think you shared the same content of this repository instead of your minting code. 
If you changed the content of this repo locally try to include the equivalent changes to the PR I shared above. I am afraid we do not have enough resources to review the ZIP you shared.
